### PR TITLE
Modularize project for diverse test cases

### PR DESCRIPTION
**Pull request by skytin1004**
# Modularize project for diverse test cases

## Summary

This pull request modularize project to facilitate testing across various use cases. It consolidates and organizes the code into distinct modules, centralizes configuration, and prepares the project for easier expansion and maintenance.

## Details of Changes

1. **Refactored Project Structure:**
    - Reorganized the project into a modular structure with separate directories for configurations, image processing, text translation, and utilities.

2. **Centralized Configuration:**
    - Created a `Config` class to manage all configuration settings.

3. **Font Management:**
    - Moved the `NotoSans-Medium.ttf` font file into a  `fonts` directory.
    - Updated the font path references in the code to reflect the new location.

4. **Image and Text Processing Modules:**
    - Created `azure_vision_translator.py` for handling image analysis and translation using Azure services.
    - Created `openai_translator.py` for handling text translation using OpenAI services.
    - Included utility functions in `image_utils.py`, `text_utils.py` for image processing tasks.

5. **Testing Infrastructure:**
    - Established a directory structure for unit tests, with separate tests for each module.
    - Created initial test files to validate the functionality of the image processing and translation modules.
    - Included a template for integration tests to ensure that all components work together seamlessly.

## Notes

- The current PR focuses on the modularization and initial testing setup.
- More comprehensive tests covering a wider range of cases will be developed once this PR is merged.
- A Jupyter notebook version that utilizes the modularized code is not included in this PR and will be created subsequently.

### CODE REVIEW

**Comment by skytin1004** [comment]
Hi @timothycdc,

I've completed the modularization and initial testing of the project. Both Azure OpenAI and Azure Computer Vision are working well in the unit tests.

The current tests are primarily for validation purposes and don't yet cover a wide range of scenarios. I plan to develop more comprehensive tests once this PR is merged.

Could you please review the PR when you have some time? If you have any questions or need further clarification, please feel free to leave a comment.

**Comment by timothycdc** [comment]
Hey @skytin1004, looks good to me. 

Wanted to know why you have separatea Production and Development configs.

Also, will you continue on `notebook_for_module_project.ipynb`?

**Comment by skytin1004** [comment]
Thank you @timothycdc ,

### Regarding Production and Development configs

I separated config(development, production) to ensure that the project can be easily scaled and maintained across different environments. 

However, if you feel that this approach isn't aligned with the current direction of the project, I'm open to removing the `development.py` and `production.py` files for now. We can always reintroduce them later if needed.

### Regarding the notebook_for_module_project.ipynb
I plan to continue working on it and will keep the notebook updated as the modules evolve. I intend to rework it into a modular version, but if there are more important issues, I'm happy to prioritize those first.

**Comment by timothycdc** [comment]
Let's keep development and production py as-is, I think this would be ok.
What are your thoughts on creating a Python library for automating translations of files/images etc? 
If so then I think the configs for dev and prod will be helpful.

Thanks for continuing to work on the other python notebook. Will merge your PR

**Comment by skytin1004** [comment]
@timothycdc I think it's a great idea
 Automating the creation of translation folders with simple commands would be really useful

One suggestion I have is to develop a Python library where you can input a country language code directly in the terminal (e.g., `translate zh-cn`) to automatically translate and save the results in a designated folder. This would greatly streamline the process. Additionally, using a command like `translate all` to handle translations for all supported languages at once would be a great feature. It would also be great to include an option to easily update translations to the latest version with just a single command

**Pull request merged**
